<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'Members\Caseproof\GrowthTools\App' => $strauss_src . '/caseproof/growth-tools/src/App.php',
   'Members\Caseproof\GrowthTools\Config' => $strauss_src . '/caseproof/growth-tools/src/Config.php',
   'Members\Caseproof\GrowthTools\Helper\AddonInstallSkin' => $strauss_src . '/caseproof/growth-tools/src/Helper/AddonInstallSkin.php',
   'Members\Caseproof\GrowthTools\Helper\AddonHelper' => $strauss_src . '/caseproof/growth-tools/src/Helper/AddonHelper.php',
);