name: Question
description: "For discussions, inquiries, or clarifications that aren't bug reports"
labels:
  - question
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What information are you seeking or what topic needs clarification?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any background information or context for this question

  - type: textarea
    id: relevant-examples
    attributes:
      label: Relevant Examples
      description: If applicable, provide examples or scenarios related to your question

  - type: input
    id: support-ticket
    attributes:
      label: Support Ticket Link (if applicable)
      description: If this question originated from a customer inquiry, provide the ticket link
      placeholder: "https://help.caseproof.com/conversation/######"

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any other relevant details or resources
